name: trudd_track_your_buddy
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_polyline_points: ^2.0.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  latlong2: ^0.9.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  web_socket_channel: ^2.4.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/google_map/dark_theme.json

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
